security:
    encoders:
        CAD\Bundle\HushBundle\Entity\Users:
            algorithm: bcrypt
            cost: 12

    providers:
        main:
            entity:
                class: HushBundle:Users
                property: username
                manager_name: ~

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /login_check/
                login_path: /
                csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /

    access_control:
      - { path: ^/(.+), roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }