hush_homepage:
    pattern:  /
    defaults: { _controller: HushBundle:Default:index }

login_check:
    path: /login_check/

logout:
    path:   /logout/

_messages:
    resource: "@HushBundle/Controller/MessagesController.php"
    type:     annotation
    prefix:   /

_users:
    resource: "@HushBundle/Controller/UsersController.php"
    type:     annotation
    prefix:   /

_user_relationships:
    resource: "@HushBundle/Controller/UserRelationshipController.php"
    type:     annotation
    prefix:   /

chat:
    path: /chat
    defaults: 
        _controller: FrameworkBundle:Template:template
        template: "HushBundle:Static:chat.php.twig" 
