hush_homepage:
    pattern:  /
    defaults: { _controller: HushBundle:Default:index }

login:
    path:     /login/
    defaults: { _controller: HushBundle:Security:login }

login_check:
    path: /login_check/

logout:
    path:   /logout/

_messages:
    resource: "@HushBundle/Controller/MessagesController.php"
    type:     annotation
    prefix:   /

_users:
    resource: "@HushBundle/Controller/UsersController.php"
    type:     annotation
    prefix:   /
