parameters:
#    hush.example.class: CAD\Bundle\HushBundle\Example

services:
  relationship_checker:
    class: CAD\Bundle\HushBundle\Helpers\RelationshipChecker
    arguments:
      entityManager: "@doctrine.orm.entity_manager"
